version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: mq

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_report
    ports:
      - "5432:5432"

  app:
    image: 'orders-report:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - rabbitmq
    # Política de reinício porque o rabbitmq demora a permitir o acesso
    restart: on-failure
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/orders_report
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - JPA_HIBERNATE_DLL_AUTO=update
      - JPA_SHOW_SQL=true
      - ORDERS_QUEUE=ordersQueue
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASSWORD=mq
    ports:
      - "8080:8080"